# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Git Projects\PYGT5\pyqt-calculator-app\calc Stuff\login.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 400)
        MainWindow.setMinimumSize(QtCore.QSize(600, 400))
        MainWindow.setMaximumSize(QtCore.QSize(600, 400))
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(600, 400))
        self.centralwidget.setMaximumSize(QtCore.QSize(600, 400))
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.LblLogin = QtWidgets.QLabel(self.centralwidget)
        self.LblLogin.setGeometry(QtCore.QRect(20, 10, 761, 41))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.LblLogin.setFont(font)
        self.LblLogin.setStyleSheet("")
        self.LblLogin.setObjectName("LblLogin")
        self.LblUsername = QtWidgets.QLabel(self.centralwidget)
        self.LblUsername.setGeometry(QtCore.QRect(30, 90, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.LblUsername.setFont(font)
        self.LblUsername.setStyleSheet("")
        self.LblUsername.setObjectName("LblUsername")
        self.LblPassword = QtWidgets.QLabel(self.centralwidget)
        self.LblPassword.setGeometry(QtCore.QRect(30, 200, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.LblPassword.setFont(font)
        self.LblPassword.setStyleSheet("")
        self.LblPassword.setObjectName("LblPassword")
        self.LnEdtUsername = QtWidgets.QLineEdit(self.centralwidget)
        self.LnEdtUsername.setGeometry(QtCore.QRect(50, 140, 501, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.LnEdtUsername.setFont(font)
        self.LnEdtUsername.setObjectName("LnEdtUsername")
        self.LnEdtPassword = QtWidgets.QLineEdit(self.centralwidget)
        self.LnEdtPassword.setGeometry(QtCore.QRect(50, 250, 501, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.LnEdtPassword.setFont(font)
        self.LnEdtPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.LnEdtPassword.setObjectName("LnEdtPassword")
        self.BtnSubmit = QtWidgets.QPushButton(self.centralwidget)
        self.BtnSubmit.setGeometry(QtCore.QRect(310, 330, 271, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.BtnSubmit.setFont(font)
        self.BtnSubmit.setStyleSheet("color: rgb(80, 80, 80);")
        self.BtnSubmit.setObjectName("BtnSubmit")
        self.BtnClear = QtWidgets.QPushButton(self.centralwidget)
        self.BtnClear.setGeometry(QtCore.QRect(20, 330, 271, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.BtnClear.setFont(font)
        self.BtnClear.setStyleSheet("color: rgb(80, 80, 80);")
        self.BtnClear.setObjectName("BtnClear")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 60, 601, 16))
        self.line.setStyleSheet("color: rgb(59, 59, 59);")
        self.line.setLineWidth(2)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.LblLogin.setText(_translate("MainWindow", "Log in to your calculator!"))
        self.LblUsername.setText(_translate("MainWindow", "Username:"))
        self.LblPassword.setText(_translate("MainWindow", "Password:"))
        self.BtnSubmit.setText(_translate("MainWindow", "Submit"))
        self.BtnClear.setText(_translate("MainWindow", "Clear"))
