# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Git Projects\PYGT5\pyqt-calculator-app\CalculatorUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Calculator(object):
    def setupUi(self, Calculator):
        Calculator.setObjectName("Calculator")
        Calculator.resize(448, 641)
        Calculator.setMinimumSize(QtCore.QSize(448, 638))
        Calculator.setMaximumSize(QtCore.QSize(502, 790))
        self.centralwidget = QtWidgets.QWidget(Calculator)
        self.centralwidget.setStyleSheet("QWidget {\n"
"    background-color: black;\n"
"    color: white;\n"
"    font: 24pt \"Comic Sans\";\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: rgb(70, 70, 70);\n"
"    border: 2px solid;\n"
"    border-radius: 10px;\n"
"    margin: 1px;\n"
"    float: 1px;\n"
"}\n"
"\n"
"#allClear{\n"
"    color:black;\n"
"    background-color:rgb(157, 157, 157)\n"
"}\n"
"\n"
"#plusMinus{\n"
"    color:black;\n"
"    background-color:rgb(157, 157, 157)\n"
"}\n"
"\n"
"#science{\n"
"    font:12pt \"Comic Sans\";\n"
"    color:black;\n"
"    background-color:rgb(157, 157, 157)\n"
"}\n"
"\n"
"#multiply{\n"
"    background-color:orange\n"
"}\n"
"\n"
"#subtract{\n"
"    background-color:orange\n"
"}\n"
"\n"
"#add{\n"
"    background-color:orange\n"
"}\n"
"\n"
"#divide{\n"
"    background-color:orange\n"
"}\n"
"\n"
"#equals{\n"
"    background-color:orange\n"
"}\n"
"\n"
"#screen{\n"
"    font:30pt \"Comic Sans\";\n"
"}\n"
"\n"
"#currentCalc{\n"
"    font:15pt \"Comic Sans\";\n"
"    color:rgb(255, 255, 0);\n"
"}\n"
"QPushButton::hover{\n"
"background-color:rgb(170, 170, 255);\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.allClear = QtWidgets.QPushButton(self.centralwidget)
        self.allClear.setGeometry(QtCore.QRect(120, 90, 101, 101))
        self.allClear.setObjectName("allClear")
        self.science = QtWidgets.QPushButton(self.centralwidget)
        self.science.setGeometry(QtCore.QRect(10, 90, 101, 101))
        self.science.setMaximumSize(QtCore.QSize(101, 101))
        self.science.setObjectName("science")
        self.plusMinus = QtWidgets.QPushButton(self.centralwidget)
        self.plusMinus.setGeometry(QtCore.QRect(230, 90, 101, 101))
        self.plusMinus.setObjectName("plusMinus")
        self.divide = QtWidgets.QPushButton(self.centralwidget)
        self.divide.setGeometry(QtCore.QRect(340, 90, 101, 101))
        self.divide.setObjectName("divide")
        self.eight = QtWidgets.QPushButton(self.centralwidget)
        self.eight.setGeometry(QtCore.QRect(120, 200, 101, 101))
        self.eight.setObjectName("eight")
        self.multiply = QtWidgets.QPushButton(self.centralwidget)
        self.multiply.setGeometry(QtCore.QRect(340, 200, 101, 101))
        self.multiply.setObjectName("multiply")
        self.seven = QtWidgets.QPushButton(self.centralwidget)
        self.seven.setGeometry(QtCore.QRect(10, 200, 101, 101))
        self.seven.setObjectName("seven")
        self.nine = QtWidgets.QPushButton(self.centralwidget)
        self.nine.setGeometry(QtCore.QRect(230, 200, 101, 101))
        self.nine.setObjectName("nine")
        self.five = QtWidgets.QPushButton(self.centralwidget)
        self.five.setGeometry(QtCore.QRect(120, 310, 101, 101))
        self.five.setObjectName("five")
        self.subtract = QtWidgets.QPushButton(self.centralwidget)
        self.subtract.setGeometry(QtCore.QRect(340, 310, 101, 101))
        self.subtract.setObjectName("subtract")
        self.four = QtWidgets.QPushButton(self.centralwidget)
        self.four.setGeometry(QtCore.QRect(10, 310, 101, 101))
        self.four.setObjectName("four")
        self.six = QtWidgets.QPushButton(self.centralwidget)
        self.six.setGeometry(QtCore.QRect(230, 310, 101, 101))
        self.six.setObjectName("six")
        self.two = QtWidgets.QPushButton(self.centralwidget)
        self.two.setGeometry(QtCore.QRect(120, 420, 101, 101))
        self.two.setObjectName("two")
        self.add = QtWidgets.QPushButton(self.centralwidget)
        self.add.setGeometry(QtCore.QRect(340, 420, 101, 101))
        self.add.setObjectName("add")
        self.one = QtWidgets.QPushButton(self.centralwidget)
        self.one.setGeometry(QtCore.QRect(10, 420, 101, 101))
        self.one.setObjectName("one")
        self.three = QtWidgets.QPushButton(self.centralwidget)
        self.three.setGeometry(QtCore.QRect(230, 420, 101, 101))
        self.three.setObjectName("three")
        self.equals = QtWidgets.QPushButton(self.centralwidget)
        self.equals.setGeometry(QtCore.QRect(340, 530, 101, 101))
        self.equals.setObjectName("equals")
        self.zero = QtWidgets.QPushButton(self.centralwidget)
        self.zero.setGeometry(QtCore.QRect(10, 530, 211, 101))
        self.zero.setObjectName("zero")
        self.decimalPoint = QtWidgets.QPushButton(self.centralwidget)
        self.decimalPoint.setGeometry(QtCore.QRect(230, 530, 101, 101))
        self.decimalPoint.setObjectName("decimalPoint")
        self.Screen = QtWidgets.QLabel(self.centralwidget)
        self.Screen.setGeometry(QtCore.QRect(10, 30, 421, 51))
        self.Screen.setObjectName("Screen")
        self.valueDisplay = QtWidgets.QLabel(self.centralwidget)
        self.valueDisplay.setGeometry(QtCore.QRect(180, 0, 241, 31))
        self.valueDisplay.setText("")
        self.valueDisplay.setObjectName("valueDisplay")
        self.operatorDisplay = QtWidgets.QLabel(self.centralwidget)
        self.operatorDisplay.setGeometry(QtCore.QRect(0, 0, 51, 31))
        self.operatorDisplay.setText("")
        self.operatorDisplay.setObjectName("operatorDisplay")
        Calculator.setCentralWidget(self.centralwidget)

        self.retranslateUi(Calculator)
        QtCore.QMetaObject.connectSlotsByName(Calculator)

    def retranslateUi(self, Calculator):
        _translate = QtCore.QCoreApplication.translate
        Calculator.setWindowTitle(_translate("Calculator", "MainWindow"))
        self.allClear.setText(_translate("Calculator", "AC"))
        self.science.setText(_translate("Calculator", "Science"))
        self.plusMinus.setText(_translate("Calculator", "+/-"))
        self.divide.setText(_translate("Calculator", "÷"))
        self.eight.setText(_translate("Calculator", "8"))
        self.multiply.setText(_translate("Calculator", "x"))
        self.seven.setText(_translate("Calculator", "7"))
        self.nine.setText(_translate("Calculator", "9"))
        self.five.setText(_translate("Calculator", "5"))
        self.subtract.setText(_translate("Calculator", "-"))
        self.four.setText(_translate("Calculator", "4"))
        self.six.setText(_translate("Calculator", "6"))
        self.two.setText(_translate("Calculator", "2"))
        self.add.setText(_translate("Calculator", "+"))
        self.one.setText(_translate("Calculator", "1"))
        self.three.setText(_translate("Calculator", "3"))
        self.equals.setText(_translate("Calculator", "="))
        self.zero.setText(_translate("Calculator", "0"))
        self.decimalPoint.setText(_translate("Calculator", "."))
        self.Screen.setText(_translate("Calculator", "<html><head/><body><p align=\"right\">0</p></body></html>"))
